"""Emit look_data.rs from a joint-fit npz, plus verification vectors for
the look.rs unit tests. Handles 1/3 curves, any LUT size, linear/MLP
predictor, optional portable maker features and scene clip.

Usage: fitenv/bin/python export_joint.py joint_XXX.npz > /path/look_data.rs
       (verification vectors go to stderr)
"""

import json
import sys
from pathlib import Path

import numpy as np
import torch

import fit_joint as fj

HERE = Path(__file__).parent


def fmt(arr, per_line=8):
    vals = [f"{v:.6}f32" for v in np.asarray(arr, dtype=np.float64).ravel()]
    return ",\n    ".join(
        ", ".join(vals[i : i + per_line]) for i in range(0, len(vals), per_line))


def main():
    path = sys.argv[1]
    npz = np.load(HERE / path, allow_pickle=True)
    cfg = json.loads(str(npz["config"]))
    err = float(npz["err"])
    dev = "cpu"
    data = fj.load_data(dev, maker=cfg.get("maker", "none"))
    ship = fj.load_shipped()
    if cfg.get("dual_matrix") or cfg.get("basis_luts", 1) > 1:
        raise SystemExit("emission for dual-matrix / basis-LUT models not wired yet")
    model = fj.Look(ship, data["n_img"], data["feats_np"], curves=cfg["curves"],
                    lut_n=cfg["lut"], predictor=cfg["predictor"], init="shipped",
                    seed=cfg["seed"], latent_extra=cfg.get("latent_extra", 0),
                    clip_scene=cfg.get("clip_scene", 0.0),
                    clip_cross=cfg.get("clip_cross", False),
                    hidden=cfg.get("hidden", 16))
    sd = {k: torch.tensor(npz[k]) for k in npz.files
          if k not in ("err", "oracle", "config")}
    model.load_state_dict(sd, strict=False)

    with torch.no_grad():
        M = model.matrix().numpy()
        knots = model.knots().numpy()          # (curves, K)
        lut = model.lut().numpy()              # (n^3, 3)
    n = cfg["lut"]
    nc = cfg["curves"]
    K = knots.shape[1]
    nf = data["feats_np"].shape[1]

    out = [f"//! GENERATED by tools/camera-look (joint fit, held-out {err:.3f}).",
           "#![allow(clippy::excessive_precision)]", ""]
    out.append(f"pub const CLIP_SCENE: f32 = {cfg.get('clip_scene', 0.0):.6};")
    out.append(f"pub const CLIP_CROSS: bool = {str(bool(cfg.get('clip_cross'))).lower()};")
    out.append("pub const MATRIX: [[f32; 3]; 3] = [")
    for r in range(3):
        out.append(f"    [{M[r][0]:.6}, {M[r][1]:.6}, {M[r][2]:.6}],")
    out.append("];")
    out.append(f"pub const CURVE_X0: f32 = {model.x0:.6};")
    out.append(f"pub const CURVE_DX: f32 = {model.dx:.6};")
    out.append(f"pub const N_CURVES: usize = {nc};")
    out.append(f"pub const CURVE_KNOTS: [[f32; {K}]; {nc}] = [")
    for c in range(nc):
        out.append(f"    [{fmt(knots[c])}],")
    out.append("];")
    out.append(f"pub const LUT_N: usize = {n};")
    out.append(f"pub const LUT: [f32; {n**3 * 3}] = [")
    out.append(f"    {fmt(lut)}")
    out.append("];")
    out.append(f"pub const N_FEATURES: usize = {nf};")
    out.append(f"pub const N_TUNING: usize = {model.latent_dim};")

    with torch.no_grad():
        if cfg["predictor"] == "linear":
            W = model.pred.numpy()  # (nf, 4)
            out.append("pub const PREDICTOR_HIDDEN: usize = 0;")
            for i, name in enumerate(["W_GAIN", "W_CONTRAST", "W_WB_R", "W_WB_B"]):
                out.append(f"pub const {name}: [f32; {nf}] = [")
                out.append(f"    {fmt(W[:, i])}")
                out.append("];")
        else:
            w1 = model.mlp1.weight.numpy()   # (h, nf)
            b1 = model.mlp1.bias.numpy()
            w2 = model.mlp2.weight.numpy()   # (n_tuning, h)
            b2 = model.mlp2.bias.numpy()
            h = w1.shape[0]
            nt = model.latent_dim
            out.append(f"pub const PREDICTOR_HIDDEN: usize = {h};")
            out.append(f"pub const MLP_W1: [f32; {h * nf}] = [\n    {fmt(w1)}\n];")
            out.append(f"pub const MLP_B1: [f32; {h}] = [\n    {fmt(b1)}\n];")
            out.append(f"pub const MLP_W2: [f32; {nt * h}] = [\n    {fmt(w2)}\n];")
            out.append(f"pub const MLP_B2: [f32; {nt}] = [\n    {fmt(b2)}\n];")
    # ---- residual k-NN over the training rows ----
    # The MLP fits the bulk; the camera's odd per-shot decisions (the
    # Contrast2012 extremes) live in the tail. A distance-weighted k-NN on
    # the MLP's residuals, faded to zero far from the corpus, fixes the
    # lookalike frames without touching generalisation.
    lat_file = HERE / (path.replace(".npz", "_latents.npy"))
    if lat_file.exists():
        lat = np.load(lat_file)
    else:
        import fit_joint as fj2
        lat = fj2.fit_test_latents(model, data, steps=500).numpy()
        np.save(lat_file, lat)
    with torch.no_grad():
        mlp_pred = model.predict(torch.tensor(data["feats_np"])).numpy()
    rows_tr = data["is_train"] & ~data["bad"]
    resid = (lat - mlp_pred)[rows_tr]
    Xtr = data["feats_np"][rows_tr]
    mu = Xtr.mean(0)
    sd = Xtr.std(0) + 1e-6
    Xw = (Xtr - mu) / sd
    # typical 4-NN distance inside the corpus (leave-one-out)
    from sklearn.neighbors import NearestNeighbors
    nn = NearestNeighbors(n_neighbors=5).fit(Xw)
    d, _ = nn.kneighbors(Xw)
    far = float(np.percentile(d[:, 1:].mean(1), 90))
    n_tr = len(Xw)
    out2 = []
    out2.append("pub const KNN_K: usize = 4;")
    out2.append(f"pub const KNN_N: usize = {n_tr};")
    out2.append(f"pub const KNN_FAR: f32 = {far:.6};")
    out2.append(f"pub const KNN_MU: [f32; {nf}] = [\n    {fmt(mu)}\n];")
    out2.append(f"pub const KNN_SD: [f32; {nf}] = [\n    {fmt(sd)}\n];")
    out2.append(f"pub const KNN_X: [f32; {n_tr * nf}] = [\n    {fmt(Xw)}\n];")
    out2.append(f"pub const KNN_R: [f32; {n_tr * model.latent_dim}] = [\n    {fmt(resid)}\n];")
    print("\n".join(out))
    print("\n".join(out2))

    # ---- verification vectors (stderr) ----
    e = sys.stderr
    tun = torch.tensor([[-0.31, 0.07, -0.05, 0.03]])
    if model.latent_dim > 4:
        tun = torch.cat([tun, torch.zeros(1, model.latent_dim - 4)], dim=1)
    pix = torch.tensor([
        [0.005, 0.004, 0.003], [0.18, 0.18, 0.18], [0.6, 0.3, 0.1],
        [1.4, 1.1, 0.9], [0.02, 0.30, 0.05], [3.5, 3.2, 2.8],
        [0.0, 0.0, 0.0], [0.09, 0.12, 0.35],
    ])
    with torch.no_grad():
        res = model(pix, tun.expand(len(pix), -1)).numpy()
        # look.rs compares in DISPLAY-LINEAR space (before srgb encode is
        # folded in): tests feed linear and expect linear back, so emit the
        # decoded value.
        def srgb_decode(v):
            v = np.clip(v, 0, 1)
            return np.where(v <= 0.04045, v / 12.92, ((v + 0.055) / 1.055) ** 2.4)
        lin = srgb_decode(res)
    print("pixel test cases (tuning gain -0.31, contrast 0.07, wb_r -0.05, wb_b 0.03),", file=e)
    print("model output is ENCODED sRGB; linear equivalents also shown:", file=e)
    for a, b, c in zip(pix.numpy(), res, lin):
        print(f"    ([{a[0]:.6}, {a[1]:.6}, {a[2]:.6}], [{b[0]:.6}, {b[1]:.6}, {b[2]:.6}])  lin [{c[0]:.6}, {c[1]:.6}, {c[2]:.6}]", file=e)

    ref = 0
    while data["bad"][ref]:
        ref += 1
    X = data["feats_np"]
    with torch.no_grad():
        p = model.predict(torch.tensor(X[ref : ref + 1])).numpy()[0]
    print(f"\nfeature test case (tag {data['entries'][ref]['tag']}):", file=e)
    print("    " + ", ".join(f"{v:.7}" for v in X[ref]), file=e)
    names = ["gain", "contrast", "wb_r", "wb_b", "saturation"][: model.latent_dim]
    for i, k in enumerate(names):
        print(f"    {k}: {p[i]:.5f}", file=e)


if __name__ == "__main__":
    main()
