// @ts-nocheck
// GENERATED by tauri-specta — do not edit by hand.

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async scanFolder(path: string) : Promise<Result<FileEntry[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("scan_folder", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listSubdirs(path: string) : Promise<Result<DirEntry[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_subdirs", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getMetadata(path: string) : Promise<Result<ImageMeta, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_metadata", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async newEpoch() : Promise<number> {
    return await TAURI_INVOKE("new_epoch");
},
async requestThumbnails(paths: string[], epoch: number) : Promise<void> {
    await TAURI_INVOKE("request_thumbnails", { paths, epoch });
},
/**
 * Count images per folder off the main thread, emitting one event per
 * result — cloud-backed folders (Dropbox, iCloud) can take seconds each,
 * so this must never block the tree display.
 */
async requestDirCounts(paths: string[]) : Promise<void> {
    await TAURI_INVOKE("request_dir_counts", { paths });
},
/**
 * Read per-image metadata (dimensions, EXIF) for the stats panel off the
 * main thread, emitting batched events. Sequential on one thread — gentle
 * on cloud-backed folders — and epoch-guarded so a folder change stops it.
 */
async requestMeta(paths: string[], epoch: number) : Promise<void> {
    await TAURI_INVOKE("request_meta", { paths, epoch });
}
}

/** user-defined events **/


export const events = __makeEvents__<{
dirCountReady: DirCountReady,
metaBatchReady: MetaBatchReady,
thumbnailFailed: ThumbnailFailed,
thumbnailReady: ThumbnailReady
}>({
dirCountReady: "dir-count-ready",
metaBatchReady: "meta-batch-ready",
thumbnailFailed: "thumbnail-failed",
thumbnailReady: "thumbnail-ready"
})

/** user-defined constants **/



/** user-defined types **/

/**
 * Direct image count of one folder, computed in the background. Keyed by
 * absolute path, so it is never stale — no epoch needed.
 */
export type DirCountReady = { path: string; imageCount: number }
export type DirEntry = { path: string; name: string }
export type ExifSubset = { orientation: number; dateTime: string | null; camera: string | null; 
/**
 * Decimal degrees; positive = north/east.
 */
gpsLat: number | null; gpsLon: number | null }
export type FileEntry = { path: string; name: string; size: number; modifiedMs: number; 
/**
 * Lowercased extension, e.g. "png".
 */
formatHint: string }
export type ImageMeta = { 
/**
 * None when no Rust decoder knows the format (e.g. AVIF) — the webview
 * can still measure the image it renders natively.
 */
width: number | null; height: number | null; format: string; fileSize: number; modifiedMs: number; exif: ExifSubset | null }
/**
 * A batch of per-image metadata read in the background for the stats panel.
 */
export type MetaBatchReady = { items: MetaEntry[]; epoch: number }
export type MetaEntry = { path: string; meta: ImageMeta }
export type ThumbnailFailed = { path: string; error: string; epoch: number }
export type ThumbnailReady = { path: string; 
/**
 * Absolute path of the cached WebP (or the original file when no codec
 * matched and the webview should decode it natively).
 */
cacheFile: string; epoch: number }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
