// @ts-nocheck
// GENERATED by tauri-specta — do not edit by hand.

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * Entries arrive as `ScanBatch` events (last marked `done`), epoch-guarded so a newer scope cancels the walk.
 */
async scanFolder(path: string, recursive: boolean, epoch: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("scan_folder", { path, recursive, epoch }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listSubdirs(path: string) : Promise<Result<DirEntry[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_subdirs", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getMetadata(path: string) : Promise<Result<ImageMeta, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_metadata", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Never prompts (confirmation is the frontend's job) and never reports more as trashed than actually went.
 */
async deleteFiles(paths: string[]) : Promise<Result<TrashOutcome, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_files", { paths }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Copies file references, not pixel data — a paste receives the files themselves.
 */
async copyFiles(paths: string[]) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("copy_files", { paths }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Also stops the watcher: a remote scope never re-watches and would otherwise leak one.
 */
async newEpoch() : Promise<number> {
    return await TAURI_INVOKE("new_epoch");
},
async requestThumbnails(paths: string[], epoch: number) : Promise<void> {
    await TAURI_INVOKE("request_thumbnails", { paths, epoch });
},
/**
 * Results arrive as `DirCountReady` events, one per folder.
 */
async requestDirCounts(paths: string[]) : Promise<void> {
    await TAURI_INVOKE("request_dir_counts", { paths });
},
/**
 * Results arrive as `MetaBatchReady` events, epoch-guarded.
 */
async requestMeta(paths: string[], epoch: number) : Promise<void> {
    await TAURI_INVOKE("request_meta", { paths, epoch });
},
async embeddingModels() : Promise<EmbedModelInfo[]> {
    return await TAURI_INVOKE("embedding_models");
},
/**
 * Downloads on first use; progress arrives as `embedding-status` events.
 */
async embeddingSelect(modelId: string) : Promise<void> {
    await TAURI_INVOKE("embedding_select", { modelId });
},
/**
 * Progress arrives as `embedding-progress` events.
 */
async embeddingIndex(paths: string[], epoch: number) : Promise<void> {
    await TAURI_INVOKE("embedding_index", { paths, epoch });
},
async embeddingRankImage(anchor: string, paths: string[]) : Promise<Result<SimilarityScore[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("embedding_rank_image", { anchor, paths }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async embeddingRankText(query: string, paths: string[]) : Promise<Result<SimilarityScore[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("embedding_rank_text", { query, paths }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * scores[i][d-1] compares paths[i] with paths[i-d]; null until indexed — never computes vectors itself.
 */
async embeddingBandedScores(paths: string[], band: number) : Promise<Result<((number | null)[])[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("embedding_banded_scores", { paths, band }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Progress arrives as `faces-progress` events.
 */
async facesIndex(paths: string[], epoch: number) : Promise<void> {
    await TAURI_INVOKE("faces_index", { paths, epoch });
},
/**
 * Also propagates identity onto near-identical faceless photos.
 */
async facesPeople(paths: string[], threshold: number, merge: number, propagate: number) : Promise<Result<PersonCluster[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("faces_people", { paths, threshold, merge, propagate }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * An empty name un-names; naming two fragments alike merges them on the next clustering.
 */
async facesRename(clusterId: string, name: string, merge: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("faces_rename", { clusterId, name, merge }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async facesNames() : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("faces_names") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Computed from the cached thumbnail, not the original.
 */
async imageStats(path: string) : Promise<Result<ImageStats, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("image_stats", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async labelsForPaths(paths: string[]) : Promise<Result<Partial<{ [key in string]: ImageLabels }>, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("labels_for_paths", { paths }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async labelsSetStars(paths: string[], stars: number | null) : Promise<Result<Partial<{ [key in string]: ImageLabels }>, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("labels_set_stars", { paths, stars }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async labelsToggleTag(paths: string[], tag: string) : Promise<Result<Partial<{ [key in string]: ImageLabels }>, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("labels_toggle_tag", { paths, tag }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async developState(path: string) : Promise<Result<DevelopState, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("develop_state", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Fetched rather than duplicated in TypeScript: the preset numbers live only in `imgvwr_develop`.
 */
async developPresets() : Promise<Result<Preset[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("develop_presets") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Returns stops, measured from the recorded light rather than the current preview.
 */
async developAutoExposure(path: string, settings: DevelopSettings) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("develop_auto_exposure", { path, settings }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async developFocusPoint(path: string, settings: DevelopSettings) : Promise<Result<[number, number], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("develop_focus_point", { path, settings }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Pixels are fetched separately over the `develop:` protocol using the returned token.
 */
async developRender(path: string, settings: DevelopSettings, maxEdge: number, overlay: Overlay, region: RegionArg) : Promise<Result<DevelopFrame, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("develop_render", { path, settings, maxEdge, overlay, region }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async developSave(path: string, settings: DevelopSettings) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("develop_save", { path, settings }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async developReset(path: string) : Promise<Result<DevelopState, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("develop_reset", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async developEditedPaths(paths: string[]) : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("develop_edited_paths", { paths }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Whole-frame crops are omitted: only crops that actually take something are returned.
 */
async developCrops(paths: string[]) : Promise<Result<Partial<{ [key in string]: Crop }>, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("develop_crops", { paths }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * One file per call, not a batch: the UI owns progress, cancellation and order.
 */
async developExport(job: ExportJob, plan: ExportPlan) : Promise<Result<Exported, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("develop_export", { job, plan }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async developPickWhiteBalance(path: string, x: number, y: number, settings: DevelopSettings) : Promise<Result<WhiteBalance, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("develop_pick_white_balance", { path, x, y, settings }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Writes nothing: the merge stays virtual until Export.
 */
async developSetFusions(fusions: Partial<{ [key in string]: FusionRecipe }>) : Promise<void> {
    await TAURI_INVOKE("develop_set_fusions", { fusions });
}
}

/** user-defined events **/


export const events = __makeEvents__<{
dirCountReady: DirCountReady,
embeddingProgress: EmbeddingProgress,
embeddingStatus: EmbeddingStatus,
facesProgress: FacesProgress,
folderChanged: FolderChanged,
metaBatchReady: MetaBatchReady,
scanBatch: ScanBatch,
thumbnailFailed: ThumbnailFailed,
thumbnailReady: ThumbnailReady
}>({
dirCountReady: "dir-count-ready",
embeddingProgress: "embedding-progress",
embeddingStatus: "embedding-status",
facesProgress: "faces-progress",
folderChanged: "folder-changed",
metaBatchReady: "meta-batch-ready",
scanBatch: "scan-batch",
thumbnailFailed: "thumbnail-failed",
thumbnailReady: "thumbnail-ready"
})

/** user-defined constants **/



/** user-defined types **/

/**
 * The camera's per-shot auto grade in Adobe slider units, from the raw file's XMP packet.
 */
export type CameraGrade = { contrast: number; saturation: number; clarity: number; texture: number }
/**
 * The rectangle in normalised original-frame coordinates; the rectangle itself is axis-aligned in the frame rotated by `angle`.
 */
export type Crop = { x: number; y: number; width: number; height: number; 
/**
 * Degrees clockwise; positive straightens a horizon that falls to the right.
 */
angle: number }
/**
 * Pixels live under `token`, fetched via the `develop:` protocol; the histogram comes inline.
 */
export type DevelopFrame = { token: number; width: number; height: number; source: FrameSource; histogram: Histogram; 
/**
 * The covered part of the frame, normalised: unit rect for a full-frame preview, the developed crop for a 1:1 detail.
 */
regionX: number; regionY: number; regionWidth: number; regionHeight: number }
/**
 * Zero means unchanged on every slider, so [`Default`] is the identity edit; ranges are ±100 except exposure (stops).
 */
export type DevelopParams = { 
/**
 * Stops of exposure; ±5 EV.
 */
exposure: number; 
/**
 * S-curve strength around middle grey; ±100.
 */
contrast: number; 
/**
 * Recovers (negative) or opens up (positive) the bright end; ±100.
 */
highlights: number; 
/**
 * Lifts (positive) or deepens (negative) the dark end; ±100.
 */
shadows: number; 
/**
 * Moves the white point; ±100.
 */
whites: number; 
/**
 * Moves the black point; ±100.
 */
blacks: number; 
/**
 * How softly the brightest values approach white, 0–100: zero clips at white, above zero bends
 * the top into an asymptote. One-sided because there is nothing on the other side of clipping.
 */
rolloff: number; 
/**
 * Saturation weighted towards already-dull colours; ±100.
 */
vibrance: number; 
/**
 * Flat saturation; ±100.
 */
saturation: number }
export type DevelopSettings = { whiteBalance: WhiteBalance; params: DevelopParams; crop: Crop; 
/**
 * The preset this edit was built on — stored, not derived: it cannot be recovered from the
 * numbers and is what the sliders measure deviation from. An id, so improving a preset
 * improves everything based on it; an unknown id reads as the identity.
 */
basis: string; 
/**
 * The fitted camera look applied under the sliders; `"flat"` means none.
 * Defaults independently of `basis`: edits saved before the look existed already emulate it
 * in slider positions, and applying the look to them too would render twice as strong.
 */
look?: string }
export type DevelopState = { width: number; height: number; asShot: WhiteBalance; settings: DevelopSettings; edited: boolean; 
/**
 * True when the webview cannot display this file itself.
 */
needsRender: boolean; hdr: HdrOutcome }
/**
 * Keyed by absolute path, so it is never stale — hence no epoch.
 */
export type DirCountReady = { path: string; imageCount: number }
export type DirEntry = { path: string; name: string }
export type EmbedModelInfo = { id: string; label: string; quality: string; speed: string; downloadMb: number; dim: number; downloaded: boolean; active: boolean }
export type EmbeddingProgress = { done: number; total: number; epoch: number }
/**
 * `phase` runs "downloading" → "loading" → "ready", or "error".
 */
export type EmbeddingStatus = { modelId: string; phase: string; error: string | null }
export type ExifSource = { kind: "none" } | { kind: "file"; path: string }
export type ExifSubset = { orientation: number; dateTime: string | null; camera: string | null; lens: string | null; exposureTime: number | null; fNumber: number | null; iso: number | null; 
/**
 * EV; Some(0.0) is the dial at its detent, distinct from unrecorded (None).
 */
exposureBias: number | null; 
/**
 * Millimetres, as marked on the lens.
 */
focalLength: number | null; 
/**
 * Decimal degrees; positive = north/east.
 */
gpsLat: number | null; gpsLon: number | null }
export type ExportFormat = { kind: "jpeg"; quality: number } | { kind: "png" }
export type ExportJob = 
/**
 * Settings are not in the job: they are already saved in `develop.db`.
 */
{ kind: "render"; path: string; exif: ExifSource } | { kind: "copy"; path: string }
export type ExportPlan = { folder: string; format: ExportFormat; size: ExportSize }
export type ExportSize = 
/**
 * Never more than the source holds: an export is not an upscaler.
 */
{ kind: "full" } | { kind: "longest"; pixels: number }
export type Exported = { source: string; 
/**
 * Not always the name asked for: an export never overwrites an existing file.
 */
path: string; 
/**
 * True only for the byte-for-byte case — a resized copy re-encodes and reports false.
 */
copied: boolean }
export type FacesProgress = { done: number; total: number; epoch: number }
export type FileEntry = { path: string; name: string; size: number; modifiedMs: number; 
/**
 * Lowercased extension, e.g. "png".
 */
formatHint: string }
/**
 * The whole re-scanned list, not a diff: coalesced or dropped OS events make diffs wrong.
 */
export type FolderChanged = { entries: FileEntry[]; epoch: number }
export type FrameSource = "cameraJpeg" | "rawDevelop"
export type FusionRecipe = { frames: string[]; method: HdrMethod }
export type HdrMethod = 
/**
 * Mertens exposure fusion — deliberately no knobs.
 */
"fusion" | 
/**
 * Scene-linear radiance, headroom kept above 1.0; the develop tone controls are the knobs.
 */
"radiance"
export type HdrOutcome = { kind: "plain" } | 
/**
 * `left_out` names frames that were misaligned and left out rather than ghosted in.
 */
{ kind: "fused"; frames: number; leftOut: string[] } | 
/**
 * The path shows the face file alone; `reason` is the measurement that said no.
 */
{ kind: "refused"; frames: number; reason: string }
/**
 * 256-bin distributions of the *developed* image — what the user is actually
 * looking at, so clipping shown here is clipping they can see. (The info
 * panel's histogram is a different thing: it describes the file on disk.)
 */
export type Histogram = { luma: number[]; red: number[]; green: number[]; blue: number[]; 
/**
 * Pixels pinned at 0 and at 255 — the numbers behind a clipping warning.
 */
clippedShadows: number; clippedHighlights: number }
/**
 * `stars` is genuinely absent until rated; `tags` is the full (possibly empty) set.
 */
export type ImageLabels = { stars: number | null; tags: string[] }
export type ImageMeta = { 
/**
 * None when no Rust decoder knows the format (e.g. AVIF).
 */
width: number | null; height: number | null; format: string; fileSize: number; modifiedMs: number; exif: ExifSubset | null; 
/**
 * Present only for files carrying the camera's XMP recipe (raw files).
 */
grade: CameraGrade | null }
/**
 * Computed from the cached thumbnail; the original is never re-decoded for stats.
 */
export type ImageStats = { 
/**
 * 256-bin histograms: Rec. 709 luma and the three channels.
 */
luma: number[]; red: number[]; green: number[]; blue: number[]; 
/**
 * Maxwell-triangle density: ▲ cells at `[b*N + a]` for a + b ≤ N-1, ▽ for a + b ≤ N-2 (a, b = barycentric red/green × N).
 * Both vectors are N×N with structurally empty slots at zero.
 */
triangleN: number; triUp: number[]; triDown: number[] }
export type MetaBatchReady = { items: MetaEntry[]; epoch: number }
export type MetaEntry = { path: string; meta: ImageMeta }
export type Overlay = "none" | 
/**
 * Tint regions by how much fine detail they resolve — the focus map.
 */
"sharpness" | "clipping"
export type PersonCluster = { 
/**
 * A named person's id IS their name (it survives reclustering); unnamed clusters get run ordinals.
 */
id: string; name: string | null; cover: string; chips: string[]; photos: string[]; solo: string[]; few: string[]; background: string[]; 
/**
 * Faceless photos near-identical to a member — the person turned away between shots.
 */
implied: string[] }
export type Preset = { id: string; 
/**
 * What the control says when this preset is the one in effect.
 */
label: string; 
/**
 * One line on what it does, for the panel to show beneath.
 */
note: string; params: DevelopParams }
/**
 * Mirrors `imgvwr_core::Region`, which deliberately carries no serde attributes.
 */
export type RegionArg = { x: number; y: number; width: number; height: number }
export type ScanBatch = { entries: FileEntry[]; epoch: number; done: boolean }
export type SimilarityScore = { path: string; score: number }
export type ThumbnailFailed = { path: string; error: string; epoch: number }
export type ThumbnailReady = { path: string; 
/**
 * The cached WebP — or the original file when no codec matched and the webview decodes natively.
 */
cacheFile: string; epoch: number }
export type TrashFailure = { path: string; error: string }
export type TrashOutcome = { 
/**
 * Only paths that actually reached the Trash — exactly what the collection may drop.
 */
removed: string[]; failed: TrashFailure[] }
/**
 * Kelvin plus green–magenta tint; higher temperature renders warmer, positive tint more magenta (the Lightroom/Core Image convention).
 */
export type WhiteBalance = { temperature: number; tint: number }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
