//! The camera look: the transform that renders a neutral raw decode the way
//! the camera's own JPEG engine would have.
//!
//! Fitted, not designed — and refitted end to end: every number below came
//! out of one joint gradient fit over ~1050 matched NEF+JPEG pairs (many
//! restarts, per-image latents distilled into the predictor). The pieces,
//! in application order:
//!
//! 1. a per-channel clamp at [`data::CLIP_SCENE`] — the camera clips before
//!    its colour math, and without this far-over-range chroma (UV stage
//!    lights) leaks through the matrix into green;
//! 2. a fixed 3×3 **matrix** — the difference between the decoder's colour
//!    and Nikon's;
//! 3. **per-image tuning** — a gain, a contrast and a white-balance nudge.
//!    Predicted by a small MLP from the image's own histogram plus the
//!    per-shot decisions the camera wrote into the file (its Auto Picture
//!    Control choices surface in the NEF's XMP packet);
//! 4. fixed per-channel **tone curves** from scene light to display — one
//!    per channel, which is what desaturates highlights into white the way
//!    the camera does;
//! 5. a 3D **lattice** over the display cube for the hue-dependent residue
//!    (Nikon turns greens yellower and reds warmer than any matrix can) —
//!    identity-regularised and clamped, so colours the fit never saw pass
//!    through nearly untouched.
//!
//! The numbers live in [`crate::look_data`], generated by the fitting
//! scripts (tools/camera-look); this module only executes them.

use imgvwr_core::{CameraDecisions, LinearImage, WhiteBalance};

use crate::look_data as data;
use crate::pipeline::luma;

/// Middle grey, the pivot the per-image contrast turns around.
const PIVOT: f32 = 0.18;

/// The per-image half of the look. Everything else in the look is a
/// constant of the camera; these follow the photograph: gain, contrast and
/// the white-balance nudges in EV, saturation as a log2 chroma scale (the
/// camera's Auto Picture Control varies saturation per shot too).
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct LookTuning {
    pub gain: f32,
    pub contrast: f32,
    pub wb_r: f32,
    pub wb_b: f32,
    pub saturation: f32,
    /// Edge-preserving NR strengths for 1:1-scale renders, from the ISO
    /// ramps the patch measurements fitted — the camera smooths high-ISO
    /// frames far beyond what the decoder's own knobs reach.
    pub chroma_nr: f32,
    pub luma_nr: f32,
}

impl LookTuning {
    /// The identity tuning: exactly the fitted global look, no per-image
    /// adjustment and no extra noise reduction.
    pub const NEUTRAL: LookTuning = LookTuning {
        gain: 0.0,
        contrast: 0.0,
        wb_r: 0.0,
        wb_b: 0.0,
        saturation: 0.0,
        chroma_nr: 0.0,
        luma_nr: 0.0,
    };
}

impl LookTuning {
    /// The camera's per-shot decisions, predicted from the frame itself and
    /// from what the camera wrote about its own choices.
    ///
    /// `iso` and the as-shot balance feed the predictor because the camera's
    /// JPEGs brighten dim high-ISO frames differently and its Auto white
    /// balance pulls casts out by an amount that depends on the illuminant.
    /// `decisions` carries the per-shot XMP/EXIF fields; pass
    /// `&CameraDecisions::default()` when the file has none — the predictor
    /// was trained with the same neutral fallbacks.
    pub fn measure(
        image: &LinearImage,
        iso: Option<u32>,
        as_shot: WhiteBalance,
        decisions: &CameraDecisions,
    ) -> Self {
        let f = features(image, iso, as_shot, decisions);
        let mut p = predict(&f);
        let c = knn_correction(&f);
        for (pi, ci) in p.iter_mut().zip(c.iter()) {
            *pi += ci;
        }
        // NR strengths from ISO alone: chroma from ~ISO 5000 (fading out
        // where luminance NR takes over, which measured better alone at the
        // extreme), luminance from ~ISO 18000. Log-ISO ramps, patch-fitted.
        let ramp = |iso_f: f32, lo: f32, hi: f32| {
            ((iso_f.log2() - lo.log2()) / (hi.log2() - lo.log2())).clamp(0.0, 1.0)
        };
        let iso_f = iso.unwrap_or(0).max(1) as f32;
        Self {
            gain: p[0].clamp(-1.5, 1.5),
            contrast: p[1].clamp(-0.5, 0.5),
            wb_r: p[2].clamp(-0.5, 0.5),
            wb_b: p[3].clamp(-0.5, 0.5),
            saturation: if data::N_TUNING > 4 {
                p[4].clamp(-1.0, 1.0)
            } else {
                0.0
            },
            chroma_nr: ramp(iso_f, 3200.0, 6400.0) * (1.0 - ramp(iso_f, 16000.0, 25600.0)),
            luma_nr: ramp(iso_f, 12800.0, 25600.0),
        }
    }
}

/// The tail of the predictor: a distance-weighted k-NN over the fitting
/// corpus's residuals (what the MLP got wrong per training image).
///
/// The MLP fits the bulk; the camera's odd per-shot decisions — the
/// Picture Control extremes on backlit fountains and UV-lit stages — recur
/// as lookalike frames, and their residuals transfer. The correction fades
/// to zero away from the corpus so an unfamiliar shoot falls back to the
/// MLP alone.
fn knn_correction(f: &[f32; data::N_FEATURES]) -> [f32; data::N_TUNING] {
    let mut fw = [0.0f32; data::N_FEATURES];
    for i in 0..data::N_FEATURES {
        fw[i] = (f[i] - data::KNN_MU[i]) / data::KNN_SD[i];
    }
    // The K nearest training rows by L2, tracked as a tiny insertion sort.
    let mut best = [(f32::INFINITY, 0usize); data::KNN_K];
    for row in 0..data::KNN_N {
        let base = row * data::N_FEATURES;
        let mut d2 = 0.0f32;
        for i in 0..data::N_FEATURES {
            let d = fw[i] - data::KNN_X[base + i];
            d2 += d * d;
        }
        if d2 < best[data::KNN_K - 1].0 {
            best[data::KNN_K - 1] = (d2, row);
            best.sort_unstable_by(|a, b| a.0.total_cmp(&b.0));
        }
    }
    let mut out = [0.0f32; data::N_TUNING];
    let mut wsum = 0.0f32;
    let mut dmean = 0.0f32;
    for (d2, row) in best {
        let d = d2.sqrt();
        dmean += d / data::KNN_K as f32;
        let w = 1.0 / d.max(1e-6);
        wsum += w;
        for k in 0..data::N_TUNING {
            out[k] += w * data::KNN_R[row * data::N_TUNING + k];
        }
    }
    let fade = ((2.0 * data::KNN_FAR - dmean) / data::KNN_FAR).clamp(0.0, 1.0);
    for o in out.iter_mut() {
        *o *= fade / wsum.max(1e-6);
    }
    out
}

/// The fitted predictor: features → tuning, a tanh MLP small enough to live
/// in constants.
fn predict(f: &[f32; data::N_FEATURES]) -> [f32; data::N_TUNING] {
    const H: usize = data::PREDICTOR_HIDDEN;
    let mut hidden = [0.0f32; H];
    for (j, h) in hidden.iter_mut().enumerate() {
        let mut acc = data::MLP_B1[j];
        for (i, x) in f.iter().enumerate() {
            acc += data::MLP_W1[j * data::N_FEATURES + i] * x;
        }
        *h = acc.tanh();
    }
    let mut out = [0.0f32; data::N_TUNING];
    for (k, o) in out.iter_mut().enumerate() {
        let mut acc = data::MLP_B2[k];
        for (j, h) in hidden.iter().enumerate() {
            acc += data::MLP_W2[k * H + j] * h;
        }
        *o = acc;
    }
    out
}

/// The scalar chains (contrast → per-channel curve) sampled densely over
/// log2 of the channel value, so the per-pixel work is one log2 and a lerp
/// per channel. The sRGB encode that follows saturation gets its own small
/// table over [0, 1].
///
/// One set of tables per render rather than per pixel: the chain depends on
/// the tuning, and the samples cost microseconds.
pub struct LookTables {
    /// Display-linear curve output over `log2(v)` ∈ [`TABLE_LO`, `TABLE_HI`],
    /// one table per channel.
    lin: [Vec<f32>; 3],
    /// sRGB encode over display-linear [0, 1].
    enc: Vec<f32>,
    /// Channel gains folded from the tuning's gain and white-balance nudge.
    gains: [f32; 3],
    /// Chroma scale around luma, from the tuning's saturation (log2).
    sat: f32,
}

const TABLE_LO: f32 = -16.0;
const TABLE_HI: f32 = 6.0;
const TABLE_N: usize = 4096;
const ENC_N: usize = 2048;

/// sRGB encode, on already-clamped display-linear input.
fn srgb_encode(v: f32) -> f32 {
    if v <= 0.003_130_8 {
        v * 12.92
    } else {
        1.055 * v.powf(1.0 / 2.4) - 0.055
    }
}

fn srgb_decode(v: f32) -> f32 {
    if v <= 0.040_45 {
        v / 12.92
    } else {
        ((v + 0.055) / 1.055).powf(2.4)
    }
}

impl LookTables {
    pub fn new(tuning: &LookTuning) -> Self {
        let k = tuning.contrast.exp2();
        let pivot_log = PIVOT.log2();
        let channel = |knots: &[f32]| -> Vec<f32> {
            (0..TABLE_N)
                .map(|i| {
                    let l = TABLE_LO + (TABLE_HI - TABLE_LO) * i as f32 / (TABLE_N - 1) as f32;
                    // Contrast is a power law around the pivot: linear in log2.
                    let l = pivot_log + (l - pivot_log) * k;
                    // The fitted curve, indexed on its own log2 grid.
                    let pos =
                        ((l - data::CURVE_X0) / data::CURVE_DX).clamp(0.0, (knots.len() - 1) as f32);
                    let i0 = (pos as usize).min(knots.len() - 2);
                    let t = pos - i0 as f32;
                    (knots[i0] * (1.0 - t) + knots[i0 + 1] * t).clamp(0.0, 1.0)
                })
                .collect()
        };
        let curve = |c: usize| &data::CURVE_KNOTS[c.min(data::N_CURVES - 1)];
        Self {
            lin: [channel(curve(0)), channel(curve(1)), channel(curve(2))],
            enc: (0..ENC_N)
                .map(|i| srgb_encode(i as f32 / (ENC_N - 1) as f32))
                .collect(),
            gains: [
                (tuning.gain + tuning.wb_r).exp2(),
                tuning.gain.exp2(),
                (tuning.gain + tuning.wb_b).exp2(),
            ],
            sat: tuning.saturation.exp2(),
        }
    }

    #[inline]
    fn scalar(&self, v: f32, c: usize) -> f32 {
        let l = v.max(1e-9).log2();
        let pos = ((l - TABLE_LO) / (TABLE_HI - TABLE_LO) * (TABLE_N - 1) as f32)
            .clamp(0.0, (TABLE_N - 1) as f32);
        let i0 = (pos as usize).min(TABLE_N - 2);
        let t = pos - i0 as f32;
        self.lin[c][i0] * (1.0 - t) + self.lin[c][i0 + 1] * t
    }

    /// sRGB encode of display-linear [0,1], via the sampled table.
    #[inline]
    fn encode(&self, v: f32) -> f32 {
        let pos = (v.clamp(0.0, 1.0) * (ENC_N - 1) as f32).min((ENC_N - 1) as f32);
        let i0 = (pos as usize).min(ENC_N - 2);
        let t = pos - i0 as f32;
        self.enc[i0] * (1.0 - t) + self.enc[i0 + 1] * t
    }
}

/// One pixel through the whole look: scene-linear RGB in, display-linear out.
#[inline]
pub fn apply_pixel(r: f32, g: f32, b: f32, tables: &LookTables) -> (f32, f32, f32) {
    // The camera clips before its colour math; without this, channels far
    // over range leak through the matrix and shift hue. CLIP_CROSS keeps
    // the full value on each channel's own (diagonal) term and clamps only
    // what crosses into the other channels; a plain clip clamps everything.
    // Values this bright render as white either way.
    let m = &data::MATRIX;
    let (r, g, b) = if data::CLIP_SCENE > 0.0 && data::CLIP_CROSS {
        let (rc, gc, bc) = (
            r.min(data::CLIP_SCENE),
            g.min(data::CLIP_SCENE),
            b.min(data::CLIP_SCENE),
        );
        (
            (m[0][0] * rc + m[0][1] * gc + m[0][2] * bc + m[0][0] * (r - rc)) * tables.gains[0],
            (m[1][0] * rc + m[1][1] * gc + m[1][2] * bc + m[1][1] * (g - gc)) * tables.gains[1],
            (m[2][0] * rc + m[2][1] * gc + m[2][2] * bc + m[2][2] * (b - bc)) * tables.gains[2],
        )
    } else {
        let (r, g, b) = if data::CLIP_SCENE > 0.0 {
            (
                r.min(data::CLIP_SCENE),
                g.min(data::CLIP_SCENE),
                b.min(data::CLIP_SCENE),
            )
        } else {
            (r, g, b)
        };
        (
            (m[0][0] * r + m[0][1] * g + m[0][2] * b) * tables.gains[0],
            (m[1][0] * r + m[1][1] * g + m[1][2] * b) * tables.gains[1],
            (m[2][0] * r + m[2][1] * g + m[2][2] * b) * tables.gains[2],
        )
    };
    let d = [
        tables.scalar(r, 0),
        tables.scalar(g, 1),
        tables.scalar(b, 2),
    ];
    // Per-image saturation around luma, in display-linear light. At the
    // neutral tuning this is exactly the identity.
    let y = luma(d[0], d[1], d[2]);
    let d = [
        (y + (d[0] - y) * tables.sat).clamp(0.0, 1.0),
        (y + (d[1] - y) * tables.sat).clamp(0.0, 1.0),
        (y + (d[2] - y) * tables.sat).clamp(0.0, 1.0),
    ];
    let e = [tables.encode(d[0]), tables.encode(d[1]), tables.encode(d[2])];
    let e = lattice(e);
    (srgb_decode(e[0]), srgb_decode(e[1]), srgb_decode(e[2]))
}

/// Trilinear lookup in the display-cube correction lattice.
#[inline]
fn lattice(e: [f32; 3]) -> [f32; 3] {
    const N: usize = data::LUT_N;
    let scale = (N - 1) as f32;
    let u = [e[0] * scale, e[1] * scale, e[2] * scale];
    let i0 = [
        (u[0] as usize).min(N - 2),
        (u[1] as usize).min(N - 2),
        (u[2] as usize).min(N - 2),
    ];
    let t = [u[0] - i0[0] as f32, u[1] - i0[1] as f32, u[2] - i0[2] as f32];
    let at = |a: usize, b: usize, c: usize| {
        let base = ((a * N + b) * N + c) * 3;
        [data::LUT[base], data::LUT[base + 1], data::LUT[base + 2]]
    };
    let mut out = [0.0f32; 3];
    for dz in 0..2 {
        for dy in 0..2 {
            for dx in 0..2 {
                let w = (if dx == 1 { t[0] } else { 1.0 - t[0] })
                    * (if dy == 1 { t[1] } else { 1.0 - t[1] })
                    * (if dz == 1 { t[2] } else { 1.0 - t[2] });
                let cell = at(i0[0] + dx, i0[1] + dy, i0[2] + dz);
                out[0] += w * cell[0];
                out[1] += w * cell[1];
                out[2] += w * cell[2];
            }
        }
    }
    [
        out[0].clamp(0.0, 1.0),
        out[1].clamp(0.0, 1.0),
        out[2].clamp(0.0, 1.0),
    ]
}

// ---------------------------------------------------------------- features

/// Fraction of each edge the statistics ignore, matching the fit: lens
/// corrections disagree most at the rim.
const BORDER: f32 = 0.06;

/// The numbers the tuning predictor reads, in the exact order it was trained
/// on: global log-luma percentiles, centre-weighted ones (the camera meters
/// the middle harder), clipping fractions, ISO, the cast of the scene, the
/// as-shot illuminant with its interactions — and then the camera's own
/// per-shot decisions from the file (XMP Picture Control terms and the EXIF
/// exposure fields), normalised exactly as the fit normalised them.
fn features(
    image: &LinearImage,
    iso: Option<u32>,
    as_shot: WhiteBalance,
    decisions: &CameraDecisions,
) -> [f32; data::N_FEATURES] {
    let (w, h) = (image.width as usize, image.height as usize);
    let (mx, my) = ((w as f32 * BORDER) as usize, (h as f32 * BORDER) as usize);
    let (iw, ih) = (w - 2 * mx, h - 2 * my);

    let mut ylog: Vec<f32> = Vec::with_capacity(iw * ih);
    let mut clip_hi = 0usize;
    let mut clip_lo = 0usize;
    let mut chan: [Vec<f32>; 3] = [
        Vec::with_capacity(iw * ih),
        Vec::with_capacity(iw * ih),
        Vec::with_capacity(iw * ih),
    ];
    for y in my..h - my {
        for x in mx..w - mx {
            let i = (y * w + x) * 3;
            let (r, g, b) = (image.rgb[i], image.rgb[i + 1], image.rgb[i + 2]);
            let yl = luma(r, g, b);
            if yl > 0.95 {
                clip_hi += 1;
            }
            if yl < 0.001 {
                clip_lo += 1;
            }
            ylog.push(yl.max(1e-8).log2());
            chan[0].push(r);
            chan[1].push(g);
            chan[2].push(b);
        }
    }

    ylog.sort_unstable_by(|a, b| a.partial_cmp(b).unwrap_or(std::cmp::Ordering::Equal));
    let gq: Vec<f32> = [1.0, 5.0, 25.0, 50.0, 75.0, 90.0, 95.0, 99.0, 99.9]
        .iter()
        .map(|q| percentile_sorted(&ylog, *q))
        .collect();

    // Centre-weighted percentiles: the middle 3/5 of the interior each way.
    let (ch, cw) = (ih / 5, iw / 5);
    let mut centre: Vec<f32> = Vec::new();
    for y in (my + 2 * ch)..(h - my - 2 * ch).max(my + 2 * ch + 1).min(h - my) {
        for x in (mx + 2 * cw)..(w - mx - 2 * cw).max(mx + 2 * cw + 1).min(w - mx) {
            let i = (y * w + x) * 3;
            centre.push(
                luma(image.rgb[i], image.rgb[i + 1], image.rgb[i + 2])
                    .max(1e-8)
                    .log2(),
            );
        }
    }
    centre.sort_unstable_by(|a, b| a.partial_cmp(b).unwrap_or(std::cmp::Ordering::Equal));
    let cq: Vec<f32> = [25.0, 50.0, 75.0, 95.0]
        .iter()
        .map(|q| percentile_sorted(&centre, *q))
        .collect();

    let med = |v: &mut Vec<f32>| -> f32 {
        v.sort_unstable_by(|a, b| a.partial_cmp(b).unwrap_or(std::cmp::Ordering::Equal));
        percentile_sorted(v, 50.0)
    };
    let (mr, mg, mb) = (
        med(&mut chan[0]).max(1e-8).log2(),
        med(&mut chan[1]).max(1e-8).log2(),
        med(&mut chan[2]).max(1e-8).log2(),
    );
    let cast_r = mr - mg;
    let cast_b = mb - mg;

    let n = (iw * ih) as f32;
    let spread = gq[8] - gq[0];
    let mid = gq[3];
    let iso_f = match iso {
        Some(v) if v > 0 => (v as f32).log2(),
        _ => 7.0,
    };
    let clip_hi = clip_hi as f32 / n;
    let t = as_shot.temperature.max(1500.0).log2() - 5000.0f32.log2();
    let ti = as_shot.tint / 100.0;

    // The camera's own decisions, with the fit's neutral fallbacks. Order
    // and normalisation mirror tools/camera-look (PORTABLE_MAKER columns).
    let d = |v: Option<f64>, fallback: f32| v.map(|x| x as f32).unwrap_or(fallback);
    let maker = [
        d(decisions.contrast, 0.0) / 25.0,
        d(decisions.saturation, 0.0) / 10.0,
        d(decisions.clarity, 0.0) / 5.0,
        d(decisions.texture, 0.0) / 10.0,
        (d(decisions.sharpness, 40.0) - 40.0) / 20.0,
        (d(decisions.luminance_smoothing, 50.0) - 50.0) / 25.0,
        d(decisions.exposure_compensation, 0.0),
        d(decisions.gain_control, 0.0),
        d(decisions.light_value, 8.0) / 10.0,
        d(decisions.exposure_program, 0.0) / 3.0,
    ];

    [
        gq[0], gq[1], gq[2], gq[3], gq[4], gq[5], gq[6], gq[7], gq[8],
        cq[0], cq[1], cq[2], cq[3],
        clip_hi,
        clip_lo as f32 / n,
        spread,
        iso_f,
        mid * spread,
        mid * mid,
        cast_r,
        cast_b,
        cast_r * cast_r,
        cast_b * cast_b,
        t,
        ti,
        t * t,
        t * cast_r,
        t * cast_b,
        iso_f * mid,
        clip_hi * spread,
        1.0,
        maker[0], maker[1], maker[2], maker[3], maker[4],
        maker[5], maker[6], maker[7], maker[8], maker[9],
    ]
}

/// numpy's default (linear-interpolated) percentile, on a sorted slice.
fn percentile_sorted(sorted: &[f32], q: f32) -> f32 {
    if sorted.is_empty() {
        return 0.0;
    }
    let pos = q / 100.0 * (sorted.len() - 1) as f32;
    let lo = pos.floor() as usize;
    let hi = (lo + 1).min(sorted.len() - 1);
    let t = pos - lo as f32;
    sorted[lo] * (1.0 - t) + sorted[hi] * t
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Pixels through the whole look against values computed independently by
    /// the fitting scripts (export_joint.py prints them at export time).
    /// Tolerance covers the sampled scalar table; anything past it is a
    /// porting mistake.
    #[test]
    fn the_look_matches_the_fit_that_produced_it() {
        let tuning = LookTuning {
            gain: -0.31,
            contrast: 0.07,
            wb_r: -0.05,
            wb_b: 0.03,
            ..LookTuning::NEUTRAL
        };
        let tables = LookTables::new(&tuning);
        for (input, expected) in PIXEL_CASES {
            let (r, g, b) = apply_pixel(input[0], input[1], input[2], &tables);
            let got = [srgb_encode(r), srgb_encode(g), srgb_encode(b)];
            for c in 0..3 {
                assert!(
                    (got[c] - expected[c]).abs() < 3e-3,
                    "{input:?} channel {c}: got {} want {}",
                    got[c],
                    expected[c]
                );
            }
        }
    }

    /// Refreshed by export_joint.py on every refit.
    const PIXEL_CASES: [([f32; 3], [f32; 3]); 8] = [
        ([0.005, 0.004, 0.003], [0.0410109, 0.0380175, 0.0322838]),
        ([0.18, 0.18, 0.18], [0.602123, 0.597791, 0.613849]),
        ([0.6, 0.3, 0.1], [1.0, 0.698797, 0.423438]),
        ([1.4, 1.1, 0.9], [0.998711, 0.995302, 0.976352]),
        ([0.02, 0.3, 0.05], [0.130384, 0.702911, 0.177245]),
        ([3.5, 3.2, 2.8], [0.999873, 0.999497, 0.999124]),
        ([0.0, 0.0, 0.0], [0.0119437, 0.0109701, 0.00812694]),
        ([0.09, 0.12, 0.35], [0.403161, 0.496078, 0.948929]),
    ];

    /// The predictor against a feature vector the fit computed for a real
    /// frame, so the weight order can never silently rotate. Refreshed by
    /// export_joint.py on every refit.
    #[test]
    fn the_tuning_predictor_matches_the_fit() {
        let p = predict(&FEATURE_CASE);
        assert!((p[0] - EXPECTED_TUNING[0]).abs() < 2e-3, "gain {}", p[0]);
        assert!((p[1] - EXPECTED_TUNING[1]).abs() < 2e-3, "contrast {}", p[1]);
        assert!((p[2] - EXPECTED_TUNING[2]).abs() < 2e-3, "wb_r {}", p[2]);
        assert!((p[3] - EXPECTED_TUNING[3]).abs() < 2e-3, "wb_b {}", p[3]);
    }

    /// Tag shoot-a_DSC_0049, features as the fit computed them.
    const FEATURE_CASE: [f32; data::N_FEATURES] = [
        -8.521706, -7.030471, -5.161331, -3.011965, -2.401099, -2.123662,
        -1.965618, -1.173384, 0.5936456, -3.252408, -2.560036, -1.984416,
        -0.3284858, 0.004176049, 0.001191287, 9.115352, 7.965784, -27.45512,
        9.071932, -0.5892315, -1.63049, 0.3471937, 2.658498, -0.03978472,
        0.3644454, 0.001582824, 0.02344241, 0.06486858, -23.99266, 0.03806615,
        1.0, -0.24, 0.2, 1.0, 0.9, 0.2, -0.04, 0.0, 0.0, 0.8695994, 0.3333333,
    ];
    const EXPECTED_TUNING: [f32; 4] = [-0.17055, -0.06570, -0.07926, -0.05438];

    /// Grey through the look may take on the camera's own small cast — the
    /// per-channel curves measured that Nikon renders the decoder's neutral
    /// grey a touch warm — but it must stay a nuance, never a colour.
    #[test]
    fn grey_keeps_at_most_the_cameras_own_cast() {
        let tables = LookTables::new(&LookTuning::NEUTRAL);
        for v in [0.02f32, 0.18, 0.5, 0.9] {
            let (r, g, b) = apply_pixel(v, v, v, &tables);
            let spread = (r.max(g).max(b) - r.min(g).min(b)) * 255.0;
            assert!(spread < 12.0, "grey {v} tinted: {r} {g} {b}");
        }
    }
}
