//! The camera look: the transform that renders a neutral raw decode the way
//! the camera's own JPEG engine would have.
//!
//! Fitted, not designed. Against ~1050 matched NEF+JPEG pairs the camera's
//! rendering decomposes into four measured pieces, applied in order:
//!
//! 1. a fixed 3×3 **matrix** — the difference between the decoder's colour
//!    and Nikon's;
//! 2. **per-image tuning** — a gain, a contrast and a white-balance nudge,
//!    predicted from the image's own histogram, because the camera meters
//!    and its Auto Picture Control decides per shot (measured spread over a
//!    third of a stop, and worth more than any other single improvement);
//! 3. a fixed per-channel **tone curve** from scene light to display — per
//!    channel rather than a luminance gain, which is what desaturates
//!    highlights into white the way the camera does;
//! 4. a small 3D **lattice** over the display cube for the hue-dependent
//!    residue (Nikon turns greens yellower and reds warmer than any matrix
//!    can) — identity-regularised and clamped, so colours the fit never saw
//!    pass through nearly untouched.
//!
//! The numbers live in [`crate::look_data`], generated by the fitting
//! scripts; this module only executes them.

use imgvwr_core::{LinearImage, WhiteBalance};

use crate::look_data as data;
use crate::pipeline::luma;

/// Middle grey, the pivot the per-image contrast turns around.
const PIVOT: f32 = 0.18;

/// The per-image half of the look, in EV. Everything else in the look is a
/// constant of the camera; these four follow the photograph.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct LookTuning {
    pub gain: f32,
    pub contrast: f32,
    pub wb_r: f32,
    pub wb_b: f32,
}

impl LookTuning {
    /// The camera's per-shot decisions, predicted from the frame itself.
    ///
    /// `iso` and the as-shot balance feed the predictor because the camera's
    /// own choices correlate with both: its JPEGs brighten dim high-ISO
    /// frames differently, and its Auto white balance pulls casts out by an
    /// amount that depends on the illuminant it measured.
    pub fn measure(image: &LinearImage, iso: Option<u32>, as_shot: WhiteBalance) -> Self {
        let f = features(image, iso, as_shot);
        let dot =
            |w: &[f32; data::N_FEATURES]| -> f32 { w.iter().zip(f.iter()).map(|(a, b)| a * b).sum() };
        Self {
            gain: dot(&data::W_GAIN).clamp(-1.5, 1.5),
            contrast: dot(&data::W_CONTRAST).clamp(-0.5, 0.5),
            wb_r: dot(&data::W_WB_R).clamp(-0.5, 0.5),
            wb_b: dot(&data::W_WB_B).clamp(-0.5, 0.5),
        }
    }
}

/// The scalar chain (contrast → curve → sRGB encode) sampled densely over
/// log2 of the channel value, so the per-pixel work is one log2 and a lerp.
///
/// One table per render rather than per pixel: the chain depends on the
/// tuning, and 4096 samples cost microseconds.
pub struct LookTables {
    /// Display-encoded output over `log2(v)` ∈ [`TABLE_LO`, `TABLE_HI`].
    enc: Vec<f32>,
    /// Channel gains folded from the tuning's gain and white-balance nudge.
    gains: [f32; 3],
}

const TABLE_LO: f32 = -16.0;
const TABLE_HI: f32 = 6.0;
const TABLE_N: usize = 4096;

/// sRGB encode, on already-clamped display-linear input.
fn srgb_encode(v: f32) -> f32 {
    if v <= 0.003_130_8 {
        v * 12.92
    } else {
        1.055 * v.powf(1.0 / 2.4) - 0.055
    }
}

fn srgb_decode(v: f32) -> f32 {
    if v <= 0.040_45 {
        v / 12.92
    } else {
        ((v + 0.055) / 1.055).powf(2.4)
    }
}

impl LookTables {
    pub fn new(tuning: &LookTuning) -> Self {
        let k = tuning.contrast.exp2();
        let pivot_log = PIVOT.log2();
        let enc = (0..TABLE_N)
            .map(|i| {
                let l = TABLE_LO + (TABLE_HI - TABLE_LO) * i as f32 / (TABLE_N - 1) as f32;
                // Contrast is a power law around the pivot: linear in log2.
                let l = pivot_log + (l - pivot_log) * k;
                // The fitted curve, indexed on its own log2 grid.
                let pos = ((l - data::CURVE_X0) / data::CURVE_DX)
                    .clamp(0.0, (data::CURVE_KNOTS.len() - 1) as f32);
                let i0 = (pos as usize).min(data::CURVE_KNOTS.len() - 2);
                let t = pos - i0 as f32;
                let display =
                    (data::CURVE_KNOTS[i0] * (1.0 - t) + data::CURVE_KNOTS[i0 + 1] * t)
                        .clamp(0.0, 1.0);
                srgb_encode(display)
            })
            .collect();
        Self {
            enc,
            gains: [
                (tuning.gain + tuning.wb_r).exp2(),
                tuning.gain.exp2(),
                (tuning.gain + tuning.wb_b).exp2(),
            ],
        }
    }

    #[inline]
    fn scalar(&self, v: f32) -> f32 {
        let l = v.max(1e-9).log2();
        let pos = ((l - TABLE_LO) / (TABLE_HI - TABLE_LO) * (TABLE_N - 1) as f32)
            .clamp(0.0, (TABLE_N - 1) as f32);
        let i0 = (pos as usize).min(TABLE_N - 2);
        let t = pos - i0 as f32;
        self.enc[i0] * (1.0 - t) + self.enc[i0 + 1] * t
    }
}

/// One pixel through the whole look: scene-linear RGB in, display-linear out.
#[inline]
pub fn apply_pixel(r: f32, g: f32, b: f32, tables: &LookTables) -> (f32, f32, f32) {
    let m = &data::MATRIX;
    let (r, g, b) = (
        (m[0][0] * r + m[0][1] * g + m[0][2] * b) * tables.gains[0],
        (m[1][0] * r + m[1][1] * g + m[1][2] * b) * tables.gains[1],
        (m[2][0] * r + m[2][1] * g + m[2][2] * b) * tables.gains[2],
    );
    let e = [tables.scalar(r), tables.scalar(g), tables.scalar(b)];
    let e = lattice(e);
    (srgb_decode(e[0]), srgb_decode(e[1]), srgb_decode(e[2]))
}

/// Trilinear lookup in the display-cube correction lattice.
#[inline]
fn lattice(e: [f32; 3]) -> [f32; 3] {
    const N: usize = data::LUT_N;
    let scale = (N - 1) as f32;
    let u = [e[0] * scale, e[1] * scale, e[2] * scale];
    let i0 = [
        (u[0] as usize).min(N - 2),
        (u[1] as usize).min(N - 2),
        (u[2] as usize).min(N - 2),
    ];
    let t = [u[0] - i0[0] as f32, u[1] - i0[1] as f32, u[2] - i0[2] as f32];
    let at = |a: usize, b: usize, c: usize| {
        let base = ((a * N + b) * N + c) * 3;
        [data::LUT[base], data::LUT[base + 1], data::LUT[base + 2]]
    };
    let mut out = [0.0f32; 3];
    for dz in 0..2 {
        for dy in 0..2 {
            for dx in 0..2 {
                let w = (if dx == 1 { t[0] } else { 1.0 - t[0] })
                    * (if dy == 1 { t[1] } else { 1.0 - t[1] })
                    * (if dz == 1 { t[2] } else { 1.0 - t[2] });
                let cell = at(i0[0] + dx, i0[1] + dy, i0[2] + dz);
                out[0] += w * cell[0];
                out[1] += w * cell[1];
                out[2] += w * cell[2];
            }
        }
    }
    [
        out[0].clamp(0.0, 1.0),
        out[1].clamp(0.0, 1.0),
        out[2].clamp(0.0, 1.0),
    ]
}

// ---------------------------------------------------------------- features

/// Fraction of each edge the statistics ignore, matching the fit: lens
/// corrections disagree most at the rim.
const BORDER: f32 = 0.06;

/// The numbers the tuning predictor reads, in the exact order it was trained
/// on: global log-luma percentiles, centre-weighted ones (the camera meters
/// the middle harder), clipping fractions, ISO, the cast of the scene (how
/// far the channel medians sit apart, which is what the camera's Auto white
/// balance responds to), and the as-shot illuminant with its interactions —
/// the same cast means something different under sodium light and daylight.
fn features(
    image: &LinearImage,
    iso: Option<u32>,
    as_shot: WhiteBalance,
) -> [f32; data::N_FEATURES] {
    let (w, h) = (image.width as usize, image.height as usize);
    let (mx, my) = ((w as f32 * BORDER) as usize, (h as f32 * BORDER) as usize);
    let (iw, ih) = (w - 2 * mx, h - 2 * my);

    let mut ylog: Vec<f32> = Vec::with_capacity(iw * ih);
    let mut clip_hi = 0usize;
    let mut clip_lo = 0usize;
    let mut chan: [Vec<f32>; 3] = [
        Vec::with_capacity(iw * ih),
        Vec::with_capacity(iw * ih),
        Vec::with_capacity(iw * ih),
    ];
    for y in my..h - my {
        for x in mx..w - mx {
            let i = (y * w + x) * 3;
            let (r, g, b) = (image.rgb[i], image.rgb[i + 1], image.rgb[i + 2]);
            let yl = luma(r, g, b);
            if yl > 0.95 {
                clip_hi += 1;
            }
            if yl < 0.001 {
                clip_lo += 1;
            }
            ylog.push(yl.max(1e-8).log2());
            chan[0].push(r);
            chan[1].push(g);
            chan[2].push(b);
        }
    }

    ylog.sort_unstable_by(|a, b| a.partial_cmp(b).unwrap_or(std::cmp::Ordering::Equal));
    let gq: Vec<f32> = [1.0, 5.0, 25.0, 50.0, 75.0, 90.0, 95.0, 99.0, 99.9]
        .iter()
        .map(|q| percentile_sorted(&ylog, *q))
        .collect();

    // Centre-weighted percentiles: the middle 3/5 of the interior each way.
    let (ch, cw) = (ih / 5, iw / 5);
    let mut centre: Vec<f32> = Vec::new();
    for y in (my + 2 * ch)..(h - my - 2 * ch).max(my + 2 * ch + 1).min(h - my) {
        for x in (mx + 2 * cw)..(w - mx - 2 * cw).max(mx + 2 * cw + 1).min(w - mx) {
            let i = (y * w + x) * 3;
            centre.push(
                luma(image.rgb[i], image.rgb[i + 1], image.rgb[i + 2])
                    .max(1e-8)
                    .log2(),
            );
        }
    }
    centre.sort_unstable_by(|a, b| a.partial_cmp(b).unwrap_or(std::cmp::Ordering::Equal));
    let cq: Vec<f32> = [25.0, 50.0, 75.0, 95.0]
        .iter()
        .map(|q| percentile_sorted(&centre, *q))
        .collect();

    let med = |v: &mut Vec<f32>| -> f32 {
        v.sort_unstable_by(|a, b| a.partial_cmp(b).unwrap_or(std::cmp::Ordering::Equal));
        percentile_sorted(v, 50.0)
    };
    let (mr, mg, mb) = (
        med(&mut chan[0]).max(1e-8).log2(),
        med(&mut chan[1]).max(1e-8).log2(),
        med(&mut chan[2]).max(1e-8).log2(),
    );
    let cast_r = mr - mg;
    let cast_b = mb - mg;

    let n = (iw * ih) as f32;
    let spread = gq[8] - gq[0];
    let mid = gq[3];
    let iso_f = match iso {
        Some(v) if v > 0 => (v as f32).log2(),
        _ => 7.0,
    };
    let clip_hi = clip_hi as f32 / n;
    let t = as_shot.temperature.max(1500.0).log2() - 5000.0f32.log2();
    let ti = as_shot.tint / 100.0;

    [
        gq[0], gq[1], gq[2], gq[3], gq[4], gq[5], gq[6], gq[7], gq[8],
        cq[0], cq[1], cq[2], cq[3],
        clip_hi,
        clip_lo as f32 / n,
        spread,
        iso_f,
        mid * spread,
        mid * mid,
        cast_r,
        cast_b,
        cast_r * cast_r,
        cast_b * cast_b,
        t,
        ti,
        t * t,
        t * cast_r,
        t * cast_b,
        iso_f * mid,
        clip_hi * spread,
        1.0,
    ]
}

/// numpy's default (linear-interpolated) percentile, on a sorted slice.
fn percentile_sorted(sorted: &[f32], q: f32) -> f32 {
    if sorted.is_empty() {
        return 0.0;
    }
    let pos = q / 100.0 * (sorted.len() - 1) as f32;
    let lo = pos.floor() as usize;
    let hi = (lo + 1).min(sorted.len() - 1);
    let t = pos - lo as f32;
    sorted[lo] * (1.0 - t) + sorted[hi] * t
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Pixels through the whole look against values computed independently by
    /// the fitting scripts (scratchpad look_vectors.json). Tolerance covers
    /// the sampled scalar table; anything past it is a porting mistake.
    #[test]
    fn the_look_matches_the_fit_that_produced_it() {
        let tuning = LookTuning {
            gain: -0.31,
            contrast: 0.07,
            wb_r: -0.05,
            wb_b: 0.03,
        };
        let tables = LookTables::new(&tuning);
        let cases: [([f32; 3], [f32; 3]); 8] = [
            ([0.005, 0.004, 0.003], [0.0495606, 0.0460665, 0.0371721]),
            ([0.18, 0.18, 0.18], [0.604055, 0.611694, 0.616314]),
            ([0.6, 0.3, 0.1], [0.967596, 0.710049, 0.458495]),
            ([1.4, 1.1, 0.9], [0.993982, 0.994928, 0.982813]),
            ([0.02, 0.3, 0.05], [0.189789, 0.733278, 0.287919]),
            ([3.5, 3.2, 2.8], [0.994558, 0.997283, 0.993702]),
            ([0.0, 0.0, 0.0], [0.0093327, 0.0110572, 0.00789953]),
            ([0.09, 0.12, 0.35], [0.412569, 0.527378, 0.911112]),
        ];
        for (input, expected) in cases {
            let (r, g, b) = apply_pixel(input[0], input[1], input[2], &tables);
            let got = [srgb_encode(r), srgb_encode(g), srgb_encode(b)];
            for c in 0..3 {
                assert!(
                    (got[c] - expected[c]).abs() < 3e-3,
                    "{input:?} channel {c}: got {} want {}",
                    got[c],
                    expected[c]
                );
            }
        }
    }

    /// The predictor against a feature vector the fit computed for a real
    /// frame (DSC_1100), so the weight order can never silently rotate.
    #[test]
    fn the_tuning_predictor_matches_the_fit() {
        let f: [f32; crate::look_data::N_FEATURES] = [
            -7.749019, -5.940775, -3.659639, -2.439431, -1.029808, -0.3455096,
            -0.03377399, 0.6891787, 0.8292179, -2.443114, -1.668773,
            -0.8296379, -0.2013228, 0.05384354, 0.002173116, 8.578237,
            10.96578, -20.92602, 5.950823, 0.9347968, -0.9222476, 0.8738451,
            0.8505407, -0.6180268, 0.04516053, 0.3819571, -0.5777295,
            0.5699737, -26.75027, 0.4618826, 1.0,
        ];
        let dot = |w: &[f32; crate::look_data::N_FEATURES]| -> f32 {
            w.iter().zip(f.iter()).map(|(a, b)| a * b).sum()
        };
        assert!((dot(&crate::look_data::W_GAIN) - -0.21759).abs() < 2e-3);
        assert!((dot(&crate::look_data::W_CONTRAST) - -0.04098).abs() < 2e-3);
        assert!((dot(&crate::look_data::W_WB_R) - -0.07954).abs() < 2e-3);
        assert!((dot(&crate::look_data::W_WB_B) - 0.03536).abs() < 2e-3);
    }

    /// Neutral grey must stay neutral through matrix and lattice: the whole
    /// look brightens and curves, but it must not tint what was grey.
    #[test]
    fn grey_stays_grey() {
        let tables = LookTables::new(&LookTuning {
            gain: 0.0,
            contrast: 0.0,
            wb_r: 0.0,
            wb_b: 0.0,
        });
        for v in [0.02f32, 0.18, 0.5, 0.9] {
            let (r, g, b) = apply_pixel(v, v, v, &tables);
            let spread = (r.max(g).max(b) - r.min(g).min(b)) * 255.0;
            assert!(spread < 6.0, "grey {v} tinted: {r} {g} {b}");
        }
    }
}
