mod commands;

use tauri_specta::{collect_commands, Builder};

fn specta_builder() -> Builder<tauri::Wry> {
    Builder::<tauri::Wry>::new()
        .commands(collect_commands![commands::scan_folder, commands::list_subdirs])
}

fn export_bindings(builder: &Builder<tauri::Wry>) {
    builder
        .export(
            specta_typescript::Typescript::default()
                // u64 fields (file size, epoch ms) stay far below 2^53, safe as JS numbers.
                .bigint(specta_typescript::BigIntExportBehavior::Number)
                // ts-nocheck: generated helpers are unused until events exist;
                // contract drift is caught at import sites and by the diff-clean check.
                .header("// @ts-nocheck\n// GENERATED by tauri-specta — do not edit by hand.\n"),
            "../src/ipc/bindings.ts",
        )
        .expect("failed to export typescript bindings");
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    let builder = specta_builder();

    #[cfg(debug_assertions)]
    export_bindings(&builder);

    tauri::Builder::default()
        .plugin(tauri_plugin_dialog::init())
        .plugin(tauri_plugin_opener::init())
        .invoke_handler(builder.invoke_handler())
        .setup(move |app| {
            builder.mount_events(app);
            Ok(())
        })
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}

#[cfg(test)]
mod tests {
    /// `pnpm gen:bindings` runs this to regenerate src/ipc/bindings.ts.
    #[test]
    fn export_bindings() {
        super::export_bindings(&super::specta_builder());
    }
}
