mod commands;
mod events;
mod services;

use std::sync::Arc;

use tauri::Manager as _;
use tauri_specta::{collect_commands, collect_events, Builder};

use services::embeddings::EmbeddingService;
use services::labels::LabelService;
use services::thumbnails::ThumbnailService;

fn specta_builder() -> Builder<tauri::Wry> {
    Builder::<tauri::Wry>::new()
        .commands(collect_commands![
            commands::scan_folder,
            commands::list_subdirs,
            commands::get_metadata,
            commands::new_epoch,
            commands::request_thumbnails,
            commands::request_dir_counts,
            commands::request_meta,
            commands::embedding_models,
            commands::embedding_select,
            commands::embedding_index,
            commands::embedding_rank_image,
            commands::embedding_rank_text,
            commands::labels_for_paths,
            commands::labels_set_stars,
            commands::labels_toggle_tag,
        ])
        .events(collect_events![
            events::ThumbnailReady,
            events::ThumbnailFailed,
            events::DirCountReady,
            events::MetaBatchReady,
            events::EmbeddingStatus,
            events::EmbeddingProgress
        ])
}

#[cfg(any(debug_assertions, test))]
fn export_bindings(builder: &Builder<tauri::Wry>) {
    builder
        .export(
            specta_typescript::Typescript::default()
                // u64 fields (file size, epoch ms) stay far below 2^53, safe as JS numbers.
                .bigint(specta_typescript::BigIntExportBehavior::Number)
                // ts-nocheck: generated helpers are unused until events exist;
                // contract drift is caught at import sites and by the diff-clean check.
                .header("// @ts-nocheck\n// GENERATED by tauri-specta — do not edit by hand.\n"),
            "../src/ipc/bindings.ts",
        )
        .expect("failed to export typescript bindings");
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    let builder = specta_builder();

    #[cfg(debug_assertions)]
    export_bindings(&builder);

    #[allow(unused_mut)]
    let mut app_builder = tauri::Builder::default()
        .plugin(tauri_plugin_dialog::init())
        .plugin(tauri_plugin_http::init())
        .plugin(tauri_plugin_opener::init());

    // MCP bridge (AI-driven testing: screenshots, DOM, IPC monitoring) — dev only.
    #[cfg(debug_assertions)]
    {
        app_builder = app_builder.plugin(tauri_plugin_mcp_bridge::init());
    }

    app_builder
        .invoke_handler(builder.invoke_handler())
        .setup(move |app| {
            builder.mount_events(app);
            let cache_root = app.path().app_cache_dir()?;
            app.manage(Arc::new(ThumbnailService::new(cache_root.join("thumbnails"))?));
            app.manage(Arc::new(EmbeddingService::new(cache_root)?));
            // Labels are user data, not a cache — they live in app data.
            let data_dir = app.path().app_data_dir()?;
            std::fs::create_dir_all(&data_dir)?;
            app.manage(Arc::new(LabelService::new(&data_dir.join("labels.db"))?));
            Ok(())
        })
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}

#[cfg(test)]
mod tests {
    /// `pnpm gen:bindings` runs this to regenerate src/ipc/bindings.ts.
    #[test]
    fn export_bindings() {
        super::export_bindings(&super::specta_builder());
    }
}
